config/routes.rb
Rafflematron::Application.routes.draw do

  
  match "winners/winner" => "winners#winner", :via => :get, :as => "winners_winner"

  match "raffle/name" => "raffle#name", :via => :get, :as => "raffle_name"
  match "raffle/type" => "raffle#type", :via => :post, :as => "raffle_type"
  match "raffle/prize" => "raffle#prize", :via => :post, :as => "raffle_prize" 
  match "raffle/completed" => "raffle#completed", :via => :post, :as => "raffle_completed"
  match "raffle/view" => "raffle#view", :via => :get, :as => "raffle_view"

  match "enter/complete" => "enter#complete", :via => :post, :as => "enter_complete"
  match "enter/show/:id" => "enter#show", :via => :get, :as => "enter_show"
  match "enter/:uri" => "enter#enter", :as => "enter_raffle"

  match "confirm/:token" => "confirm#confirm", :via => :get, :as => "confirm_entry"

  match "winners/send_mail" => "winners#send_mail", :via => :post, :as => "winner_send_mail"
  

  resources :winners do
    member do
      get :download
    end
  end
  resources :raffle
  resource :enter, :controller => "enter"

  devise_for :admins
  devise_for :users
  
  scope "/admin" do
    resources :users
  end

  root :to=>"home#index"

end

app/models/raffle.rb
class Raffle < ActiveRecord::Base
  attr_accessible :id, :name, :num_prizes, :num_entries, :raffle_owner, :uri, :start, :end
  validates_uniqueness_of :uri, :case_sensitive => false
  has_many :prize
  has_many :entries
  accepts_nested_attributes_for :prize, :allow_destroy => true
end

app/controllers/raffle_controller.rb
class RaffleController < ApplicationController
  before_filter :authenticate_user!
  helper RafflesHelper

  def index
  end

  def view
    @raffle = Raffle.find(params[:raffle_id])
    @prizes = Prize.where(:raffle_id => @raffle.id)
  end

  def update
    @raffle = Raffle.find(params[:id])
    @raffle.num_entries = params[:raffle][:num_entries]
    @raffle.editing = false
    @prizes = Prize.where(:raffle_id => @raffle.id)
    params[:raffle][:prize_attributes].each do |key, value|
      puts value
      if value[:_destroy] == "1"
        Prize.find(@prizes[key.to_i].id).destroy
        @raffle.save
      elsif @prizes[key.to_i].nil?
        prize = Prize.new
        prize.raffle_id = @raffle.id
        prize.prize_name = value["prize_name"]
        prize.photo = value["photo"]
        prize.save
        @raffle.num_prizes += 1
        @raffle.save
      else
        @prizes[key.to_i].raffle_id = @raffle.id
        if value["photo"].nil?
        else
          @prizes[key.to_i].photo = value["photo"]
        end
        @prizes[key.to_i].prize_name = value["prize_name"]
        @prizes[key.to_i].save
      end
    end
    @raffle.save
    flash[:notice] = "Edit complete"
    redirect_to winners_path
  end

  def edit
    @raffle = Raffle.find(params[:id])
    @raffle.editing = true
    @prizes = Prize.where(:raffle_id => params[:id])
  end

  def name
    @raffle = Raffle.new
  end   
 
  def type
    begin
      uri = params[:raffle][:uri]
      if params[:raffle][:uri].gsub(/[^0-9a-zA-Z]/, "-") != uri
        uri = uri.gsub(/[^0-9a-zA-Z]/, "-")
      else
        uri = params[:raffle][:uri]
      end
      @raffle = Raffle.create!(params[:raffle])
      @raffle.editing = false
      @raffle.has_winner = false
      @raffle.num_prizes = 1
      @raffle.raffle_owner = current_user.email
      @raffle.uri = uri
      @raffle.save
    rescue Exception => e
      flash[:error] = "URL Taken"
      redirect_to raffle_name_path
      puts e
    end
  end

  def prize
    @raffle = Raffle.find(params[:raffle][:id])
    @raffle.update_attributes(params[:raffle])
    @raffle.num_prizes.times do
      prize = @raffle.prize.build 
    end
  end 
  
  def completed
    @raffle = Raffle.find(params[:raffle][:id])
    @prizes = []
    @raffle.num_prizes.times { @prizes << Prize.new }
    params[:raffle][:prize_attributes].each do |key, value|
      puts value
      @prizes[key.to_i].raffle_id = @raffle.id
      @prizes[key.to_i].prize_name = value["prize_name"]
      @prizes[key.to_i].photo = value["photo"]
      @prizes[key.to_i].save
    end
  end

  def destroy
    Raffle.find(params[:id]).destroy
    flash[:notice] = "Deleted successfully"
    redirect_to winners_path
  end
end

app/helpers/raffle_helper.rb
module RaffleHelper
end

app/helpers/raffles_helper.rb
module RafflesHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end
  
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize, :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
end

app/views/raffle/_prize.html.erb
<div class = "fields">
  <div class = "control-group">
    <%= f.label "Prize Name: ", :class => "control-label" %>
    <%= f.text_field :prize_name, :class => "controls", :required => true %>
  </div>
  <div class = "control-group">
    <%= f.label "Prize Photo: ", :class => "control-label" %>
    <%= f.file_field :photo, :class => "controls" %>
  </div>
  <% if f.object.photo.url.include? "missing.png" %>
  <% else %>
    <div class = "control-group">
      <%= f.label "Current Photo: ", :class => "control-label" %>
      <%= image_tag f.object.photo.url(:thumb), :class => "controls" %>
    </div>
  <% end %>
  <% if @raffle.editing %>
    <div class = "control-group">
      <div class = "control"><%= link_to_remove_fields "remove", f %></div>
    </div>
  <% end %> 
</div>

app/views/raffle/completed.html.erb
<div class = "well span6 offset3 form-horizontal">
  <h1 class = "controls pagination-centered"><%= @raffle.name %></h1>
  <dl class = "dl-horizontal">
    <dt>Raffle ID</dt>
    <dd><%= @raffle.id %></dd>
    <dt>URL for Entry</dt>
    <dd>http://<%= request.host %>/enter/<%= @raffle.uri %></dd>
    <dt>Entries Per Person</dt>
    <% if @raffle.num_entries == 0 %>
      <dd>Unlimited</dd>
    <% else %>
      <dd><%= @raffle.num_entries %></dd>
    <% end %>
    <dt>Number of Prizes</dt>
    <dd><%= @raffle.num_prizes %></dd>
  <dl>

  <h3 class = "control">Prizes</h3>
  <dl>
    <% @prizes.each do |prize| %>
      <dt>Prize Name</dt>
      <dd><%= prize.prize_name %></dd>
      <dt>Photo</dt>
      <dd><%= image_tag prize.photo.url(:thumb) %></dd>
    <% end %>
  </dl>

  <%= link_to "Your Raffles", winners_path, :class => "btn control" %>
</div>

app/views/raffle/edit.html.erb
<%= form_for @raffle, :html => { :class => "well span6 offset3 form-horizontal" } do |f| %>
  <h1 class = "control"><%= @raffle.name %></h1>
  <%= f.hidden_field :id %>
  <div class="control-group">
    <%= f.label :name, "Name of raffle ", :class => "control-label" %>
    <%= f.text_field :name, :class => "controls" %>
  </div>
  <div class="control-group">
    <%= f.label :num_entries, "Entries per person", :class => "control-label" %>
    <%= f.text_field :num_entries, :class => "controls" %>
  </div>
  <h2 class = "control">Prizes</h2>
  <%= f.fields_for :prize do |b| %>	
    <div class = "control_group">
      <%= render :partial => "prize", :locals => { :f => b } %>
    </div>
  <% end %>
  <div class = "control-group">
  <div class = "control"><%= link_to_add_fields "Add Prize", f, :prize %></div>
  </div>
  <div class="control-group">
  <div class = "control">
    <%= link_to "Cancel", winners_path, :class => "btn" %>
    <%= f.submit "Save", :class => "btn" %>
  </div>
  </div>
<% end %>

app/views/raffle/edit_complete.erb
<!DOCTYPE html>
<html>
<body>
Hi
</body>
<html>

app/views/raffle/index.html.erb
<div class = "well span6 offset3 form-horizontal">
  <h1 class = "controls pagination-centered">Let's make a raffle</h1>
  <%= link_to "Create >>", raffle_name_path, :class => "btn control" %>
</div>

app/views/raffle/name.html.erb
<script>
$(function() { 
  $("input[id=raffle_name]").on("keyup", function() 
    {
      $("input[id=raffle_uri]").val(slug($("input[id=raffle_name]").val()))
    } 
)});

var slug = function(str) {
    var $slug = '';
    var trimmed = $.trim(str);
    $slug = trimmed.replace(/[^a-z0-9-]/gi, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
    return $slug.toLowerCase();
}
</script>

<%= form_for @raffle, :method => "post", :url => raffle_type_path, :html => { :class => "well span6 offset3 form-horizontal" } do |f| %>
  <h1 class = "controls pagination-centered">Name Your Raffle</h1>
  <div class = "control-group">
    <%= f.label :name, "Name of Raffle: ", :class => "control-label" %>
    <%= f.text_field :name, :required => true, :class => "controls", :maxsize => "25" %>
  </div>
  <div class = "control-group">
    <%= f.label :uri, "URL: http://#{request.host}/enter/", :class => "control-label" %>
    <%= f.text_field :uri, :required => true, :class => "controls" %>
  </div>
  <div class = "control-group">
    <br />
    <%= f.submit "Save", :class => "control" %>
  </div>
<% end %>

app/views/raffle/prize.html.erb
<div class = "well span6 offset3 form-horizontal">
  <div class = "control-group">
    <div class = "controls">
      <h1 class = "controls pagination-centered"><%= @raffle.name %></h1>
    </div>
  </div>
<%= form_for @raffle, :method => :post, :url => raffle_completed_path, :html => { :multipart => true } do |f| %>
  <%= f.hidden_field :id %>
  <%= f.fields_for :prize do |b| %>	
    <div class = "control_group">
      <%= render :partial => "prize", :locals => { :f => b } %>
    </div>
  <% end %>
  <div class = "control-group">
     <%= f.submit "Submit", :class => "control" %>
   </div>
<% end %>
</div>

app/views/raffle/show.html.erb
<%= form_for @raffle, :method => "post", :url => raffle_type_path do |f| %>
  <%= f.label :name, "Name of raffle: " %>
  <%= f.text_field :name %> <br />
  <%= f.label :num_prizes, "Prizes" %>
  <%= f.text_field :num_prizes %>
  <%= f.label :num_entries, "Entries per person" %>
  <%= f.text_field :num_entries %>
<% end %>

app/views/raffle/type.html.erb
<div class = "well span6 offset3 form-horizontal">
  <h1 class = "controls pagination-centered"><%= @raffle.name %></h1>
   <%= form_for @raffle, :method => :post, :url => raffle_prize_path do |r| %>
     <div class = "control-group">
       <%= r.label :q, "How many prizes?", :class => "control-label" %>
       <%= r.text_field :num_prizes, :class => "controls" %>
     </div>
     <div class = "control-group">
       <%= r.label :q, "How many entries per person? (0 for unlimited)", :class => "control-label" %>
       <%= r.text_field :num_entries, :value => "1", :class => "controls" %>
     </div>
     <div class = "control-group">
       <%= r.hidden_field :id %>
       <%= r.submit "Save", :class => "control" %>
     </div>
  <% end %>
</div>

app/views/raffle/view.html.erb
<div class = "well span6 offset3 form-horizontal">
  <h1 class = "controls pagination-centered"><%= @raffle.name %></h1>
  <dl class = "dl-horizontal">
    <dt>Raffle ID</dt>
    <dd><%= @raffle.id %></dd>
    <dt>URL for Entry</dt>
    <dd>http://<%= request.host %>/enter/<%= @raffle.uri %></dd>
    <dt>Entries Per Person</dt>
    <% if @raffle.num_entries == 0 %>
      <dd>Unlimited</dd>
    <% else %>
      <dd><%= @raffle.num_entries %></dd>
    <% end %>
    <dt>Number of Prizes</dt>
    <dd><%= @raffle.num_prizes %></dd>
  <dl>

  <h3 class = "control">Prizes</h3>
  <dl>
    <% @prizes.each do |prize| %>
      <dt>Prize Name</dt>
      <dd><%= prize.prize_name %></dd>
      <dt>Photo</dt>
      <dd><%= image_tag prize.photo.url(:thumb) %></dd>
    <% end %>
  </dl>

  <%= link_to "Go Back", winners_path, :class => "btn control" %>
</div>