config/routes.rb
Rafflematron::Application.routes.draw do

  
  match "winners/winner" => "winners#winner", :via => :get, :as => "winners_winner"

  match "raffle/name" => "raffle#name", :via => :get, :as => "raffle_name"
  match "raffle/type" => "raffle#type", :via => :post, :as => "raffle_type"
  match "raffle/prize" => "raffle#prize", :via => :post, :as => "raffle_prize" 
  match "raffle/completed" => "raffle#completed", :via => :post, :as => "raffle_completed"
  match "raffle/view" => "raffle#view", :via => :get, :as => "raffle_view"

  match "enter/complete" => "enter#complete", :via => :post, :as => "enter_complete"
  match "enter/show/:id" => "enter#show", :via => :get, :as => "enter_show"
  match "enter/:uri" => "enter#enter", :as => "enter_raffle"

  match "confirm/:token" => "confirm#confirm", :via => :get, :as => "confirm_entry"

  match "winners/send_mail" => "winners#send_mail", :via => :post, :as => "winner_send_mail"
  

  resources :winners do
    member do
      get :download
    end
  end
  resources :raffle
  resource :enter, :controller => "enter"

  devise_for :admins
  devise_for :users
  
  scope "/admin" do
    resources :users
  end

  root :to=>"home#index"

end

app/models/winner.rb
class Winner < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/winners_controller.rb
class WinnersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @raffles = Raffle.where(:raffle_owner => current_user.email)
  end

  def show
    @winners = Entry.where(:raffle_id => params[:id]).where(:winner => true)
  end

  def winner
    @entries = Entry.where(:raffle_id => params[:raffle_id])
    @raffle = Raffle.find(params[:raffle_id])
    @prizes = Prize.where(:raffle_id => params[:raffle_id])
    @winners = []
    index = 0
    winners_email = []
    @raffle.num_prizes.times do
      begin
        winner = rand(@entries.count + 1)
      end until @winners.include?(@entries[winner]) == false && @entries[winner] != nil && @entries[winner].confirmed == true && @entries[winner].winner == false && winners_email.include?(@entries[winner].email) == false 	
      @winners[index] = @entries[winner]
      @winners[index].winner = true
      @winners[index].prize = @prizes[index].prize_name
      @winners[index].save
      winners_email.push(@winners[index].email)
      index += 1
    end
    
    if @winners[0] != nil
      @raffle.has_winner = true
      @raffle.winner = @winners[0].email
      @raffle.save
    else
      flash[:notice] = "No suitible entries found"
      redirect_to winners_path
     end
  end
  
  def destroy
    Raffle.find(params[:id]).destroy
    @entries = Entry.where(:raffle_id => params[:id])
    @entries.each do |e|
      e.destroy
    end
  end

  def send_mail
    if params[:cancel] != nil
      redirect_to winners_path
    else
      @raffle = Raffle.find(params[:id])
      @winners = Entry.where(:raffle_id => params[:id]).where(:winner => true)
      @winners.each_with_index do |e, index|
        EntryMailer.message_winners(e, @raffle, params[:message]).deliver
      end
      flash[:notice] = "Emails sent"
      redirect_to winners_path
    end
  end

  def download
    @raffle = Raffle.find(params[:id])
    fname = Rails.root.to_s + "/tmp/" + current_user.email + "_entries.csv"
    if File.exists?(fname)
      File.delete(fname)
      @entries = Entry.where(:raffle_id => @raffle.id)
      File.open(fname, "a") do |file|
        @entries.each_with_index do |e, index|
          if @entries[index].name != nil || @entries[index].email != nil && @entries[index].confirmed == true
            file.puts @entries[index].name + "," + @entries[index].email
          end
        end
      end
    else
      @entries = Entry.where(:raffle_id => @raffle.id)
      File.open(fname, "a") do |file|
        @entries.each_with_index do |e, index|
          if @entries[index].name != nil || @entries[index].email != nil && @entries[index].confirmed == true
            file.puts @entries[index].name + "," + @entries[index].email
          end
        end
      end
    end
    send_file fname
  end
end

app/helpers/winners_helper.rb
module WinnersHelper
end

app/views/winners/index.html.erb
<h1 class = "pagination-centered"> Raffles </h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Entries</th>
      <th>Winner</th>
      <th>View</th>
      <th>Edit</th>
      <th>Delete</th>
      <th>Download Entries</th>
      <th>Enter Page</th>
     </tr>
   </thead>
   <tbody>
   <% if @raffles.size == 0 %>
     <tr>
       <td>Nothing here!  <%= link_to "Create Raffle", raffle_index_path %></td>
       <td></td>
       <td></td>
       <td></td>
       <td></td>
       <td></td>
       <td></td>
       <td></td>
     </tr>
   <% else %> 
     <% @raffles.each do |r| %> 
       <tr>
         <td><%= r.name %></td>
         <td><%= r.entries.size %> <%= link_to "Show", enter_show_path(:id => r.id, :page => 1) %></td>
         <% if r.has_winner == false %>
         <td><%= link_to "Choose winner", winners_winner_path(:raffle_id => r.id) %></td>
         <% else %>
         <td><%= r.winner %> <%= link_to "Show", winner_path(:id => r.id) %></td>
         <% end %>
         <td><%= link_to "View", raffle_view_path(:raffle_id => r.id) %></td>
         <td><%= link_to "Edit", edit_raffle_path(r) %></td>
         <td><%= link_to "Delete", r, :method => :delete, :class => :destroy %></td>
         <td><%= link_to "Download CSV", download_winner_path(:id => r.id) %></td>
         <td><%= link_to "http://"+ request.host + enter_raffle_path(:uri => r.uri),"http://"+ request.host + enter_raffle_path(:uri => r.uri), :target => "_blank", :confirm => "This will log you out. Is that ok?" %></td>
       </tr>
      <% end %>
    <% end %>
   </tbody>
</table> 

app/views/winners/show.html.erb
<style>
.buttons {
margin-left: 180px; 
}
</style>

<div class = "well span6 offset3 form-horizontal">
  <h1 class = "controls pagination-centered">Winners</h1>
  <dl class = "dl-horizontal">
  <% @winners.each_with_index do |w, index| %>
    <dt>Winner <%= index + 1%></dt>
    <dd><%= w.email %></dd>
    <dt>Winner <%= index + 1%> Prize</dt>
    <dd><%= w.prize %></dd>
  <% end %>
  </dl>

  <%= form_tag :controller => "winners", :action => "send_mail" do %>
  <div class = "control-group">
    <div class = "control-label"
      <%= label_tag "Add your own message to the email" %>
    </div>
    <div class = "control">
      <%= text_area_tag "message" %>
    </div>
  </div>
  <%= hidden_field_tag "id", @winners[0].raffle_id %>
  <div class = "buttons">
    <%= submit_tag "Send Emails", :name => "send" %>
    <%= submit_tag "Cancel", :name => "cancel" %>
  </div>
  <% end %>
</div>

app/views/winners/winner.html.erb
<div class = "well span6 offset3 form-horizontal">
  <h1 class = "controls pagination-centered">Winners</h1>
  <dl class = "dl-horizontal">
  <% @winners.each_with_index do |w, index| %>
    <dt>Winner <%= index + 1%></dt>
    <dd><%= w.email %></dd>
  <% end %>
  </dl>
</div>