config/routes.rb
Rafflematron::Application.routes.draw do

  
  match "winners/winner" => "winners#winner", :via => :get, :as => "winners_winner"

  match "raffle/name" => "raffle#name", :via => :get, :as => "raffle_name"
  match "raffle/type" => "raffle#type", :via => :post, :as => "raffle_type"
  match "raffle/prize" => "raffle#prize", :via => :post, :as => "raffle_prize" 
  match "raffle/completed" => "raffle#completed", :via => :post, :as => "raffle_completed"
  match "raffle/view" => "raffle#view", :via => :get, :as => "raffle_view"

  match "enter/complete" => "enter#complete", :via => :post, :as => "enter_complete"
  match "enter/show/:id" => "enter#show", :via => :get, :as => "enter_show"
  match "enter/:uri" => "enter#enter", :as => "enter_raffle"

  match "confirm/:token" => "confirm#confirm", :via => :get, :as => "confirm_entry"

  match "winners/send_mail" => "winners#send_mail", :via => :post, :as => "winner_send_mail"
  

  resources :winners do
    member do
      get :download
    end
  end
  resources :raffle
  resource :enter, :controller => "enter"

  devise_for :admins
  devise_for :users
  
  scope "/admin" do
    resources :users
  end

  root :to=>"home#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
  # attr_accessible :title, :body
end

app/models/entries.rb
class Entry < ActiveRecord::Base
  attr_accessible :name, :email, :raffle_id, :id
  belongs_to :raffle
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  before_create :generate_token
  attr_accessible :name, :email, :raffle_id, :token, :confirmed, :prize, :winner
  belongs_to :raffle

  protected
  
  def generate_token
    begin
      token = SecureRandom.urlsafe_base64
    end while Entry.where(:token => token).exists?
    self.token = token
  end
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/prize.rb
class Prize < ActiveRecord::Base
  attr_accessible :prize_name, :photo, :raffle_id
  belongs_to :raffle
  has_attached_file :photo,
    :styles => { :thumb => "100x100#" }
end

app/models/raffle.rb
class Raffle < ActiveRecord::Base
  attr_accessible :id, :name, :num_prizes, :num_entries, :raffle_owner, :uri, :start, :end
  validates_uniqueness_of :uri, :case_sensitive => false
  has_many :prize
  has_many :entries
  accepts_nested_attributes_for :prize, :allow_destroy => true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  extend FriendlyId
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :raffle

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
end

app/models/winner.rb
class Winner < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    link_to_function(name, "remove_fields(this)")
  end
  
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render("_" + association.to_s.singularize + :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
end

app/helpers/confim_helper.rb
module ConfimHelper
end

app/helpers/confirm_helper.rb
module ConfirmHelper
end

app/helpers/enter_helper.rb
module EnterHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/raffle_helper.rb
module RaffleHelper
end

app/helpers/raffles_helper.rb
module RafflesHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end
  
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize, :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/winners_helper.rb
module WinnersHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <li>
      <%= link_to "Your Raffles", winners_path %>
    </li>
    <li>
      <%= link_to "Create a Raffle", raffle_index_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin Panel', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = "shortcut icon" href = "/favicon.ico">
    <link rel = "icon" type="image/ico" href = "/favicon.ico">
    <title><%= content_for?(:title) ? yield(:title) : "Rafflematron" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>    
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/layouts/enter.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rafflematron" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>    
  </head>
  <body>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>